# Generated by Django 5.2.16 on 2026-07-22 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0034_comprehension_batches'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='subject_completed_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
