# Generated by Django 5.2.16 on 2026-07-22 07:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0035_card_subject_completed_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComprehensionTestCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='explicit_completions', to='study.comprehensiontest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comprehension_test_completions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['completed_at', 'id'],
                'constraints': [models.UniqueConstraint(fields=('user', 'test'), name='unique_comprehension_test_completion')],
            },
        ),
    ]
