# Generated by Django 5.2.16 on 2026-07-23 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0036_comprehension_test_completion'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='completed_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
