# Generated by Django 5.2.16 on 2026-07-23 21:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0037_annotation_completed_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WritingSujet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.SlugField(max_length=64)),
                ('category_label', models.CharField(max_length=80)),
                ('slug', models.SlugField(max_length=80)),
                ('order', models.PositiveIntegerField(default=0)),
                ('prompt', models.TextField()),
                ('versions', models.JSONField(default=list)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='writing_sujets', to='study.task')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PersonalWritingResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_writing_responses', to=settings.AUTH_USER_MODEL)),
                ('sujet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_versions', to='study.writingsujet')),
            ],
            options={
                'ordering': ['-updated_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='writingsujet',
            index=models.Index(fields=['task', 'category', 'order'], name='study_writi_task_id_9331dd_idx'),
        ),
        migrations.AddConstraint(
            model_name='writingsujet',
            constraint=models.UniqueConstraint(fields=('task', 'slug'), name='unique_writing_sujet_slug_per_task'),
        ),
        migrations.AddIndex(
            model_name='personalwritingresponse',
            index=models.Index(fields=['user', 'updated_at'], name='study_perso_user_id_f3c551_idx'),
        ),
        migrations.AddConstraint(
            model_name='personalwritingresponse',
            constraint=models.UniqueConstraint(fields=('user', 'sujet'), name='unique_user_writing_response'),
        ),
    ]
