# Generated by Django 5.2.16 on 2026-07-23 23:42

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0038_writingsujet_personalwritingresponse_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WritingSujetCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('sujet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='explicit_completions', to='study.writingsujet')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='writing_sujet_completions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['completed_at', 'id'],
                'constraints': [models.UniqueConstraint(fields=('user', 'sujet'), name='unique_writing_sujet_completion')],
            },
        ),
    ]
