# Generated by Django 5.2.16 on 2026-08-22 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0040_shared_tache_two_annotation_keys'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phrase',
            name='tier',
            field=models.CharField(choices=[('shared', 'Shared catalog'), ('response', 'Response vocabulary'), ('subject', 'Subject vocabulary'), ('theme', 'Theme vocabulary'), ('comprehension', 'Comprehension vocabulary')], db_index=True, default='response', max_length=16),
        ),
    ]
