# Generated by Django 5.2.16 on 2026-08-22 19:26

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0041_add_theme_vocabulary_tier'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ThemeVocabularyProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('phrase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='explicit_learning_progress', to='study.phrase')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theme_vocabulary_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['completed_at', 'id'],
                'constraints': [models.UniqueConstraint(fields=('user', 'phrase'), name='unique_theme_vocabulary_progress')],
            },
        ),
    ]
