# Generated by Django 5.2.16 on 2026-09-01 05:35

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0042_theme_vocabulary_progress'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComprehensionQuestionStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_markers', to='study.comprehensionquestion')),
                ('user', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='comprehension_question_studies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'comprehension question studies',
                'ordering': ['question__test__order', 'question__number', 'id'],
                'constraints': [models.UniqueConstraint(fields=('user', 'question'), name='unique_comprehension_question_study')],
            },
        ),
    ]
