# Generated by Django 5.2.17 on 2026-09-07 08:08

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0047_learning_lesson_progress'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lesson_id', models.CharField(max_length=80)),
                ('content_version', models.CharField(max_length=64)),
                ('mode', models.CharField(choices=[('practice', 'practice'), ('check', 'check'), ('review', 'review')], max_length=8)),
                ('status', models.CharField(choices=[('active', 'active'), ('completed', 'completed'), ('abandoned', 'abandoned')], default='active', max_length=9)),
                ('snapshot', models.JSONField()),
                ('events', models.JSONField(default=list)),
                ('results', models.JSONField(default=dict)),
                ('independent', models.BooleanField(default=False)),
                ('criterion_met', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('review_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='study.courseattempt')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at', '-id'],
                'indexes': [models.Index(fields=['user', 'lesson_id'], name='course_user_lesson_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('user', 'lesson_id', 'mode'), name='unique_active_course_attempt')],
            },
        ),
        migrations.CreateModel(
            name='CourseProduction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lesson_id', models.CharField(max_length=80)),
                ('content_version', models.CharField(max_length=64)),
                ('task_snapshot', models.JSONField()),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('self_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_productions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['user', 'lesson_id'], name='production_user_lesson_idx')],
            },
        ),
    ]
