# Generated by Django 5.2.17 on 2026-09-08 05:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0048_course_practice'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='annotation',
            index=models.Index(fields=['user', 'kind', '-created_at', '-id'], name='annotation_user_kind_created'),
        ),
        migrations.AddIndex(
            model_name='annotation',
            index=models.Index(fields=['user', 'task', 'kind', '-created_at', '-id'], name='annotation_scope_created'),
        ),
    ]
