# Generated by Django 5.2.17 on 2026-09-08 05:14

import django.db.models.deletion
from django.conf import settings
from django.db import NotSupportedError, migrations, models


class CreateExposureModel(migrations.CreateModel):
    """Old workers' deletion collectors do not know these derived tables."""

    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        vendor = schema_editor.connection.vendor
        if vendor == "sqlite":
            attribute = "sql_create_inline_fk"
            template = (
                "REFERENCES %(to_table)s (%(to_column)s) "
                "ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED"
            )
        elif vendor == "postgresql":
            attribute = "sql_create_fk"
            template = (
                "ALTER TABLE %(table)s ADD CONSTRAINT %(name)s FOREIGN KEY (%(column)s) "
                "REFERENCES %(to_table)s (%(to_column)s) ON DELETE CASCADE%(deferrable)s"
            )
        else:
            raise NotSupportedError("Course exposure cascades require SQLite or PostgreSQL.")
        original = getattr(schema_editor, attribute)
        try:
            setattr(schema_editor, attribute, template)
            super().database_forwards(app_label, schema_editor, from_state, to_state)
        finally:
            setattr(schema_editor, attribute, original)


# Future table rebuilds must preserve these native cascades, not only Django's
# ORM-level on_delete. Original attempt and user tables are deliberately untouched.


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0049_annotation_listing_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        CreateExposureModel(
            name='CourseExposureIndex',
            fields=[
                ('attempt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='exposure_index', serialize=False, to='study.courseattempt')),
            ],
        ),
        CreateExposureModel(
            name='CourseItemExposure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_id', models.CharField(max_length=80)),
                ('item_id', models.CharField(max_length=80)),
                ('exposure_key', models.CharField(max_length=64)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_exposures', to='study.courseattempt')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_item_exposures', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'exposure_key'], name='course_exposure_user_key'), models.Index(fields=['user', 'lesson_id', 'item_id'], name='course_exposure_user_item')],
                'constraints': [models.UniqueConstraint(fields=('attempt', 'item_id'), name='unique_course_item_exposure')],
            },
        ),
    ]
