# Generated by Django 5.2.17 on 2026-09-11 02:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0050_course_exposure_projection'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='source_prompt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_annotations', to='study.prompt'),
        ),
        migrations.AddField(
            model_name='personalresponse',
            name='source_prompt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personal_response_sources', to='study.prompt'),
        ),
        migrations.AddField(
            model_name='prompt',
            name='model_content',
            field=models.JSONField(blank=True, default=dict, db_default={}),
        ),
        migrations.AddField(
            model_name='response',
            name='semantic_group',
            field=models.CharField(blank=True, db_index=True, max_length=160, default='', db_default=''),
        ),
        migrations.AddField(
            model_name='response',
            name='semantic_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='historical_sources', to='study.response'),
        ),
        migrations.AddField(
            model_name='response',
            name='semantic_rationale',
            field=models.TextField(blank=True, default='', db_default=''),
        ),
        migrations.AddField(
            model_name='response',
            name='semantic_state_revision',
            field=models.CharField(blank=True, max_length=64, default='', db_default=''),
        ),
        migrations.CreateModel(
            name='OralStateSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=24)),
                ('source_id', models.PositiveBigIntegerField()),
                ('digest', models.CharField(max_length=64)),
                ('payload', models.JSONField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='state_snapshots', to='study.response')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='oral_state_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
                'constraints': [models.UniqueConstraint(fields=('kind', 'source_id', 'digest'), name='unique_oral_state_snapshot')],
            },
        ),
    ]
