# Generated by Django 5.2.17 on 2026-09-11 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0051_oral_semantic_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalresponse',
            name='is_active',
            field=models.BooleanField(default=True, db_default=True),
        ),
    ]
