# Generated by Django 5.2.17 on 2026-09-11 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0052_personal_response_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='projection_review_boundary',
            field=models.PositiveBigIntegerField(default=0, db_default=0),
        ),
    ]
