# Generated by Django 5.2.16 on 2026-09-11 22:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0053_oral_projection_undo_boundary'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WritingResponseOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_key', models.CharField(max_length=80)),
                ('body', models.TextField(blank=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sujet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='response_overrides', to='study.writingsujet')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='writing_response_overrides', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'sujet', 'version_key'), name='unique_user_writing_version')],
            },
        ),
    ]
