"""Public HTTP handlers exposed to the URL configuration."""

from .account import (
    change_pin,
    delete_account,
    export_account,
    login_view,
    logout_view,
    recover_account,
    recovery_codes_view,
    regenerate_recovery_codes,
    register_view,
    reset_progress,
    settings_view,
)
from .comprehension import (
    comprehension_group_detail,
    comprehension_hub,
    comprehension_oral_group_detail,
    comprehension_oral_overview,
    comprehension_oral_study_list,
    comprehension_overview,
    comprehension_question,
    comprehension_question_study,
    comprehension_question_study_toggle,
    comprehension_results,
    comprehension_start,
    comprehension_study_list,
    comprehension_test_completion,
    comprehension_test_detail,
)
from .dashboard import dashboard, expression_hub
from .learning import (
    learn,
    learn_lesson,
    learn_lesson_progress,
    learn_lesson_start,
)
from .library import (
    browse,
    edit_response,
    family_detail,
    part_detail,
    part_vocabulary,
    phrases,
    response_detail,
    search,
    stats,
    subject_completion,
    tache_two_theme_vocabulary,
    tache_two_theme_vocabulary_detail,
    tache_two_theme_vocabulary_progress,
    task_detail,
    task_memories,
    task_memory_detail,
    task_memory_progress,
    task_question_response,
    task_subject_batch,
    task_subject_detail,
    theme_detail,
    theme_vocabulary_progress,
    writing_response_delete,
    writing_sujet_completion,
    writing_sujet_detail,
    writing_sujet_edit,
)
from .notes import (
    annotation_complete_toggle,
    annotation_create,
    annotation_delete,
    annotation_search,
    annotation_study,
    annotation_study_toggle,
    annotation_update,
    annotations_for_source,
    comprehension_notes,
    custom_notes,
    general_notes,
    notes_overview,
    task_notes,
    translate_selection,
)
from .review import (
    review,
    review_answer,
    review_hub,
    review_next,
    review_previous,
    review_undo,
    revisit_list,
)
